#!/usr/bin/env bash
set -euo pipefail
# Hard (lexically matched) retrieval for all 11 final checkpoints + an untrained dense control, GPUs 0-3.
cd /home/zd25e122/clevr_discrete_diffusion
mkdir -p outputs/hard_retrieval_eval
tmux new-session -d -s clevr_hard_0 "cd /home/zd25e122/clevr_discrete_diffusion && exec env CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=0 PYTHONUNBUFFERED=1 /home/zd25e122/miniconda3/envs/unix/bin/python3.10 evaluate_hard_retrieval.py --num-worlds 2000 --output-dir outputs/hard_retrieval_eval --checkpoint dense_epoch003=outputs/text_dense_diffusion_2m_4e_matched/epoch_003.pt --checkpoint plain_lora_epoch003=outputs/text_lora_diffusion_2m_4e_matched/epoch_003.pt --checkpoint layerwise_gated_hsic_epoch003=outputs/text_module_jepa_layerwise_gated_hsic_2m_4e/epoch_003.pt --untrained-from outputs/text_dense_diffusion_2m_4e_matched/epoch_003.pt > outputs/hard_retrieval_eval/launcher_0.log 2>&1"
tmux new-session -d -s clevr_hard_1 "cd /home/zd25e122/clevr_discrete_diffusion && exec env CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=1 PYTHONUNBUFFERED=1 /home/zd25e122/miniconda3/envs/unix/bin/python3.10 evaluate_hard_retrieval.py --num-worlds 2000 --output-dir outputs/hard_retrieval_eval --checkpoint layerwise_no_hsic_epoch003=outputs/text_module_jepa_layerwise_no_hsic_2m_4e/epoch_003.pt --checkpoint layerwise_hsic_epoch003=outputs/text_module_jepa_layerwise_hsic_2m_4e/epoch_003.pt --checkpoint layerwise_gated_no_hsic_epoch003=outputs/text_module_jepa_layerwise_gated_no_hsic_2m_4e/epoch_003.pt > outputs/hard_retrieval_eval/launcher_1.log 2>&1"
tmux new-session -d -s clevr_hard_2 "cd /home/zd25e122/clevr_discrete_diffusion && exec env CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 PYTHONUNBUFFERED=1 /home/zd25e122/miniconda3/envs/unix/bin/python3.10 evaluate_hard_retrieval.py --num-worlds 2000 --output-dir outputs/hard_retrieval_eval --checkpoint avg_no_hsic_epoch003=outputs/text_module_jepa_avg_no_hsic_2m_4e/epoch_003.pt --checkpoint avg_hsic_epoch003=outputs/text_module_jepa_avg_hsic_2m_4e/epoch_003.pt --checkpoint avg_hsic_calibrated_old_epoch003=outputs/text_module_jepa_avg_hsic_calibrated_2m_4e/epoch_003.pt > outputs/hard_retrieval_eval/launcher_2.log 2>&1"
tmux new-session -d -s clevr_hard_3 "cd /home/zd25e122/clevr_discrete_diffusion && exec env CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=3 PYTHONUNBUFFERED=1 /home/zd25e122/miniconda3/envs/unix/bin/python3.10 evaluate_hard_retrieval.py --num-worlds 2000 --output-dir outputs/hard_retrieval_eval --checkpoint data2vec_avg_gated_epoch003=outputs/text_data2vec_avg_gated_shared_calibrated_jepa_hsic_2m_4e/epoch_003.pt --checkpoint data2vec_noavg_gated_epoch003=outputs/text_data2vec_noavg_gated_shared_calibrated_jepa_hsic_2m_4e/epoch_003.pt > outputs/hard_retrieval_eval/launcher_3.log 2>&1"
